ga-dc/garnet

app/views/layouts/application.html.erb
app/views/users/sign_in.html.erb
db/schema.rb

Added in layout.html.erb and sign_in.html.erb. In sing_in.html.erb moved login with GitHub link out of the sign in form

add GitHub font awesome icons to welcome

---

Gemfile
Gemfile.lock
app/models/assignment.rb
spec/models/assignment_spec.rb

Added specs for setting default Assignment#due_date
Using pry-byebug to support 'debugger' OR 'binding.pry'

assignment: Default due_date

---

app/controllers/users_controller.rb
app/models/user.rb
spec/models/user_spec.rb

Makes it easier to see users by squad.

Add first and last name methods to users and sort users by last name

---

app/views/assignments/index.html.erb

Assignments: add 'All'

---

app/assets/stylesheets/application.css.scss
app/controllers/application_controller.rb
app/controllers/users_controller.rb
app/views/layouts/application.html.erb
app/views/users/orphans.html.erb
config/routes.rb

For users with no memberships.

added orphans path

---

app/controllers/assignments_controller.rb
app/controllers/memberships_controller.rb
app/controllers/users_controller.rb
app/models/assignment.rb
app/models/github.rb
app/models/submission.rb
app/views/memberships/show.html.erb
app/views/submissions/_row.html.erb
app/views/users/show.html.erb
spec/models/assignment_spec.rb
spec/models/github_spec.rb

This pull request shows missing / complete status on assignments show and users show page.

Assignments

---

app/models/tree.rb

Note: Only tested against observations.  I want to work with Robin to test against other collection methods.

tree: use Set to gather descendent Observations, etc.

---

app/controllers/memberships_controller.rb
app/controllers/submissions_controller.rb

fixed getting issues and memberships by not passing arguments to #get_issues

---

Gemfile
Gemfile.lock
config/newrelic.yml
readme.md

- Uses my personal key.  If we like it, we should  get GA account.

add new relic: gem, config/newrelic.yml

---

app/views/assignments/show.html.erb
db/seeds/test_seed.rb

- seed: added testwdidcstudent
- added assignment

group issues: add link to assignment issues for this group

---

app/assets/javascripts/application.js
app/assets/stylesheets/application.css.scss

Incidentally, I like how most of us really dont know anything about him, including me.

More of a tribute to Kevin Garnett. 

---

app/controllers/events_controller.rb
app/views/events/show.html.erb

To make taking attendance easier, there is a now a link that allows the user to filter attendances where the status is nil.
At first, I thought about doing this in JS, but the url params will allow us to send the filter link to others.

add link to filter attendances

---

app/assets/javascripts/assignments.js
app/views/assignments/show.html.erb

So the table is easier to look at.

Adds a button to show / hide 'notes' in assignments

---

app/assets/stylesheets/application.css.scss

Addresses https://github.com/ga-dc/garnet/issues/176

remove hover effect from welcome screen avatar

---

app/controllers/users_controller.rb
app/models/user.rb
app/views/assignments/_form.html.erb
app/views/users/show.html.erb

Implements a number of changes to address https://github.com/ga-dc/garnet/issues/240 and https://github.com/ga-dc/garnet/issues/243
1. Adds date select field to form for assignments. Default remains current date, but this allows for creation of assignments in advance.
2. Removes submissions with status N/A from calculation of percent complete in student report card view.
3. Hides submissions from admin's to-do list until the due date. All submissions, regardless of due date or status, will still be visible on the assignment's show page, allowing access for early grading if applicable.

manual assignment of due dates for assignments

---

app/views/layouts/application.html.erb

I tested locally and didn't notice any issues.

removed jquery alpha 3

---

Gemfile
Gemfile.lock
app/controllers/memberships_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/group.rb
app/models/user.rb
app/views/groups/_form.html.erb
app/views/groups/show.html.erb
app/views/users/show.html.erb
db/migrate/20151118145509_add_ancestry_to_groups.rb
db/schema.rb
spec/models/group_spec.rb

Only real file changes were changing `path` to `path_string` in several places.
Also, reproduced existing `group#ancestors` method in the migration file itself since this method will be replaced by Ancestry's, but is necessary to convert to Ancestry in the first place.

added ancestry gem and updated files accordingly, fixes #230

---

Gemfile
Gemfile.lock
app/views/assignments/show.html.erb
spec/features/instructor_dashboard_spec.rb

- add launchy (for save_and_open_page)
Does not add functionality, just tests.  First thumbs up can merge.

submissions: add feature specs

---

Gemfile
Gemfile.lock
app/models/membership.rb
app/models/tag.rb
app/models/tagging.rb
db/migrate/20160112193921_create_tags.rb
db/migrate/20160112193925_create_taggings.rb
db/schema.rb
spec/factories/taggings.rb
spec/factories/tags.rb
spec/models/membership_spec.rb
spec/models/tag_spec.rb
spec/models/tagging_spec.rb

adds `tag` and `taggings` model as well as migrations.
adds associations to `tags`, `taggings`, `memberships`.
adds test coverage for associations for `tags` and `memberships`

adds tags and taggings table

---

app/controllers/dashboards_controller.rb
app/models/attendance.rb
app/models/membership.rb
app/models/submission.rb
app/models/user.rb

Does this by updating the get_due method to search for memberships with
tags in common with your admin memberships.

Updates todo page to show only items in your 'squad'

---

app/assets/javascripts/tags.js
app/assets/stylesheets/application.css.scss
app/controllers/taggings_controller.rb
app/helpers/tag_helper.rb
app/models/tagging.rb
app/models/user.rb
app/views/dashboards/to_do.html.erb
app/views/memberships/_table.html.erb
config/routes.rb

Also fixes bug in querying DB for shared-tag students.

Implements ability to remove tags. 

---

app/assets/javascripts/tags.js
app/assets/stylesheets/application.css.scss
app/controllers/taggings_controller.rb
app/helpers/tag_helper.rb
app/models/tagging.rb
app/models/user.rb
app/views/dashboards/to_do.html.erb
app/views/memberships/_table.html.erb
config/routes.rb

The form wasn't including the hidden membership_id correctly.

Fixes bug where observations couldn't be saved

---

Gemfile
Gemfile.lock
app/models/event.rb
db/seeds.rb

Seeds data.
Also changes validation to allow events be 1 second apart for seeds.

Seeds update

---

app/assets/javascripts/submission.js
app/controllers/assignments_controller.rb
app/controllers/submissions_controller.rb
app/models/submission.rb
app/views/assignments/_form.html.erb
app/views/assignments/show.html.erb
app/views/submissions/_table.html.erb
config/routes.rb
db/migrate/20160127182408_add_column_to_assignment.rb
db/migrate/20160127182636_add_column_to_submissions.rb
db/schema.rb

Add homework scores

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/submission.js
app/assets/stylesheets/application.css.scss
app/views/assignments/show.html.erb

Removes appending td for score updates, instead flashes green when updating score
fixes overflow for tables for long usernames

fixes #344 #346 #343

---

db/seeds.rb

Statuses are present/tardy/miissing/complete/etc.
Also uses named constants for numbers.

Updates seeds to mark subs/attendances with a status

---

app/assets/javascripts/tables.js
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/cohorts.css.scss
app/controllers/application_controller.rb
app/controllers/cohorts_controller.rb
app/controllers/memberships_controller.rb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/models/ability.rb
app/models/attendance.rb
app/models/membership.rb
app/models/submission.rb
app/views/cohorts/manage.html.erb
app/views/cohorts/show.html.erb
app/views/dashboards/to_do.html.erb
app/views/memberships/_cohort_row.html.erb
app/views/memberships/_cohorts_table.html.erb
app/views/memberships/_form.html.erb
app/views/memberships/_row.html.erb
app/views/memberships/_row_performance_cells.html.erb
app/views/memberships/_table.html.erb
app/views/users/show.html.erb
config/environments/development.rb
config/routes.rb
db/seeds.rb

Improves cohort show performance by over 66% when cache is warm.

Caching cohort show page

---

app/assets/javascripts/tables.js
app/assets/stylesheets/application.css.scss
app/assets/stylesheets/cohorts.css.scss
app/controllers/application_controller.rb
app/controllers/cohorts_controller.rb
app/controllers/memberships_controller.rb
app/controllers/users_controller.rb
app/models/ability.rb
app/models/membership.rb
app/views/cohorts/manage.html.erb
app/views/cohorts/show.html.erb
app/views/dashboards/to_do.html.erb
app/views/memberships/_cohort_row.html.erb
app/views/memberships/_cohorts_table.html.erb
app/views/memberships/_form.html.erb
app/views/memberships/_row.html.erb
app/views/memberships/_row_performance_cells.html.erb
app/views/memberships/_table.html.erb
app/views/users/show.html.erb
config/routes.rb
db/seeds.rb

Still some work to be done with removing / deactivating users.

Add cohort management page

---

Gemfile
Gemfile.lock
app/models/attendance.rb
config/schedule.rb
lib/tasks/attendance.rake

needs configuration to be run on server side still @adambray

fixes #336

---

app/assets/stylesheets/application.css.scss
app/views/memberships/show.html.erb

improves ui to only include overview in show page on initial view, but clickable dropdown for more information about events and assignments

fixes #381

---

app/controllers/cohorts_controller.rb

[#371](https://github.com/ga-dc/garnet/issues/371)

Fixes #371

---

app/views/cohorts/manage.html.erb

need to update ui to look pretty, quick implementation so we can have at least the ability to delete members for now.

jesse made me implement this feature

---

app/models/membership.rb
app/views/memberships/_row.html.erb
app/views/memberships/_table.html.erb
spec/features/cohort_spec.rb
spec/models/membership_spec.rb

adds view + specs for member's average observations

---

app/assets/stylesheets/application.css.scss
app/helpers/application_helper.rb
app/views/memberships/_row_performance_cells.html.erb

adjusts color in membership table to invert if value is negative

---

db/seeds.rb

Want to see UI with actual user images.

generate avatars for users in seeds.rb

---

app/controllers/memberships_controller.rb
app/models/user.rb

fixes observations so they only show on the correct page

---

app/helpers/application_helper.rb
app/models/assignment.rb
app/models/attendance.rb
app/models/submission.rb
spec/factories/cohorts.rb
spec/features/instructor_dashboard_spec.rb

Fixes 442 exclude inactive from todo

---

app/controllers/sessions_controller.rb

old code from when we had a global rescuer

changes raise to a flash notice and redirects to root path

---

app/models/submission.rb
app/views/assignments/_table.html.erb

Fixes #445, #446

---

app/views/assignments/_table.html.erb
app/views/events/_table.html.erb

please don't make me write a test for this

ignore inactive members for attendance percentage calculation;

---

app/assets/javascripts/application.js
app/assets/javascripts/submission.js
app/assets/stylesheets/application.css.scss

Adds 59 stylesheets and scripts just to make submissions flash when a score is entered. Changed to use existing "waiting" class instead.

Removed jQuery UI

---

app/assets/javascripts/assignments.js

should probably replace https://github.com/ga-dc/garnet/blob/ede575b801b5316f0f06a505d5936618741c384e/app/models/assignment.rb#L46 because the output is not human readable

fixes #418

---

app/assets/javascripts/application.js

AJAX method we can use as a catch-all for submitting anything, including submission statuses, scores, notes, attendance, etc...

Added autosave

---

app/controllers/attendances_controller.rb
app/helpers/application_helper.rb
app/views/assignments/show.html.erb
app/views/attendances/_thead.html.erb
app/views/attendances/_tr.html.erb
app/views/components/_delete_button.html.erb
app/views/components/_status_buttons.html.erb
app/views/components/_todo_table.html.erb
app/views/dashboards/to_do.html.erb
app/views/events/show.html.erb
app/views/submissions/_thead.html.erb
app/views/submissions/_tr.html.erb
db/seeds/test_seed.rb
spec/features/instructor_dashboard_spec.rb

Also moves attendance/submission to own partials for extra dryness.

Standardize attendances

---

app/views/cohorts/show.html.erb
app/views/memberships/show.html.erb

The pages really aren't that long without it. I think it's more of a nuisance having to expand everything all the time.

Removed folding in various places

---

db/migrate/20160302232327_add_location_course_number_to_cohorts.rb
db/schema.rb
db/seeds.rb

Ex: If you have DC WDI 8, makes 8 an actual column.

Added cohort number at location

---

app/models/assignment.rb
app/models/attendance.rb
app/models/event.rb
app/models/membership.rb
app/models/observation.rb
app/models/submission.rb
app/views/memberships/_row_performance_cells.html.erb
config/application.rb
db/migrate/20160306220325_add_averages_to_memberships.rb
db/schema.rb
lib/model_helpers.rb
spec/models/membership_spec.rb

- An alternative to using `cache` because it's kinda scary, and some data appears to not be refreshing
- percent_from_status takes status name, not number

Added membership averaging methods

---

app/views/memberships/_cohorts_table.html.erb
app/views/memberships/_row_performance_cells.html.erb
app/views/memberships/_table.html.erb

- TODO: Add coloring
- Changes % absent to % present
- Fixes https://github.com/ga-dc/garnet/issues/524

Tardies shown as number rather than percent

---

db/seeds.rb
db/seeds/common.rb

Utilizing DatabaseCleaner
Creating less seed examples

seeds: speed up, more efficient and just less

---

app/assets/stylesheets/theme.css.scss
app/controllers/api/cohorts_controller.rb
app/controllers/cohorts_controller.rb
app/views/cohorts/_form.html.erb
config/routes.rb
db/migrate/20160318191715_add_core_to_cohort.rb
db/schema.rb

Adresses (hopefully!) Tim Foley's issue [#486](https://github.com/ga-dc/garnet/issues/486)
Added to cohorts controller and form:
- Core ID
- Duration in weeks
- Day of week
Also updated the styling for the form.
I hope I did not 🔥🔥🔥🔥 anything down!

API for cohorts

---

Gemfile
Gemfile.lock
app/controllers/assignments_controller.rb
app/controllers/cohorts_controller.rb
app/controllers/events_controller.rb
app/controllers/memberships_controller.rb
app/models/cohort.rb
app/models/user.rb
app/views/assignments/show.html.erb
app/views/cohorts/manage.html.erb
app/views/components/_tag_list.html.erb
app/views/events/show.html.erb
config/environments/development.rb
config/routes.rb

Used `bullet` gem to find extra `n+1` queries, fixed by utilizing eager-loading

Active loading

---

Gemfile.lock
app/models/attendance.rb
spec/models/attendance_spec.rb

Couple of notes:
- used a setter instead of `.unmarked!` because the enum bang method fires a save
- test uses a hard coded string, while i didn't like this, couldn't figure out an easy way to get the string of the key for a certain value in the `Attendance.statuses` hash. It ended up being much cleaner and more englishy hard coding the string.

Fixes # 551

---

Gemfile.lock
app/models/attendance.rb
spec/models/attendance_spec.rb

Revert "Fixes # 551"

---

app/assets/javascripts/nav.js
app/assets/javascripts/tags-and-tables.js
app/assets/stylesheets/theme.css.scss
app/views/cohorts/show.html.erb
app/views/memberships/show.html.erb

Currently lacks tests, but getting closer to being able to merge. I would love some feedback :eyes:

Iss383 sidebar

---

app/assets/javascripts/application.js
app/assets/javascripts/nav.js
app/assets/stylesheets/theme.css.scss
app/views/memberships/show.html.erb

Fixed folding bug that prevented observations from showing

---

Gemfile.lock
app/views/cohorts/manage.html.erb
spec/features/manage_cohort_spec.rb

tests pass. Can now make members admins or de admin existing admins in cohort manage page.

Fixes #531

---

app/models/cohort.rb
app/models/mantra.rb
spec/factories/user.rb
spec/features/membership_spec.rb
spec/models/cohort_spec.rb

- converts Array results to AR Associations
- user factory derives email from username
This is preparation for dealing with Instructors in a Cohort.

cohort: convert methods to associations

---

Gemfile.lock
app/assets/javascripts/application.js
app/assets/javascripts/nav.js
app/assets/javascripts/tags-and-tables.js
app/assets/stylesheets/theme.css.scss
app/models/cohort.rb
app/models/mantra.rb
app/models/membership.rb
app/models/user.rb
app/views/cohorts/manage.html.erb
app/views/cohorts/show.html.erb
app/views/memberships/show.html.erb
lib/tasks/metrics.rake
spec/factories/user.rb
spec/features/manage_cohort_spec.rb
spec/features/membership_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/cohort_spec.rb

An updated version of [this PR](https://github.com/ga-dc/garnet/pull/513) to make tests pass.

Fixes #508 - updates memberships when users are updated - take 2

---

app/models/membership.rb

Membership: remove duplicate association code

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/controllers/application_controller.rb
app/models/cohort.rb
app/views/layouts/application.html.erb
config/application.rb
spec/models/cohort_spec.rb

- fixes time issues for rendering in different time zones
- ensures mass event creation creates event /w time zone.

Attendance server time
